export const colors = {
    lightPink: '#FFB3BA',
    peach: '#FFDFBA',
    lightYellow: '#FFFFBA',
    mintGreen: '#BAFFC9',
    skyBlue: '#BAE1FF',
    lavender: '#E2C6FF',
    blush: '#FFD6E8',
    paleAqua: '#C9F9FF',
    softLime: '#D4F1B4',
    warmBeige: '#FFE3B3',
    softViolet: '#E8D3FF',
    roseTint: '#F6CACA',
    seafoam: '#C8E9D7',
    lightSand: '#F9E2AE',
    babyBlue: '#CDE7FF',
    apricot: '#FFE6CC',
    paleLilac: '#EADCF8',
    lightMint: '#DFF5E2',
    paleButter: '#FFF5CC',
    coralTint: '#F4D8CD',
    icyBlue: '#E3F1FF',
    lightMagenta: '#FFD0F7',
    mintyWhite: '#D9FFF7'
};
